### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by D1mon** [joshuabenuck/twitch#2]
```
RUST_BACKTRACE=1 cargo run
warning: unused import: `Read`
--> src/twitch_db.rs:5:15
|
5 | use std::io::{Read, Write};
|               ^^^^
|
= note: `#[warn(unused_imports)]` on by default

warning: unused import: `Product`
--> src/twitch_game.rs:1:33
|
1 | use crate::twitch_db::{Install, Product, TwitchDb};
|                                 ^^^^^^^

warning: field is never used: `auth_scopes`
--> src/twitch_game.rs:30:5
|
30 |     auth_scopes: Option<Vec<String>>,
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default

warning: field is never used: `schema_version`
--> src/twitch_game.rs:37:5
|
37 |     schema_version: String,
|     ^^^^^^^^^^^^^^^^^^^^^^

warning: field is never used: `post_install`
--> src/twitch_game.rs:38:5
|
38 |     post_install: Option<Vec<FuelCommand>>,
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: method is never used: `load`
--> src/twitch_game.rs:110:5
|
110 |     fn load(cache_dir: PathBuf) -> Result<Vec<TwitchGame>, Error> {
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: method is never used: `save`
--> src/twitch_game.rs:117:5
|
117 |     fn save(cache_dir: &PathBuf, games: &Vec<TwitchGame>) -> Result<(), Error> {
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Finished dev [unoptimized + debuginfo] target(s) in 6.38s
Running `target/debug/twitch`
Refreshing Twitch game cache...
thread 'main' panicked at 'assertion failed: product_info_db.exists()', src/twitch_db.rs:72:9
stack backtrace:
0: backtrace::backtrace::libunwind::trace
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
1: backtrace::backtrace::trace_unsynchronized
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
2: std::sys_common::backtrace::_print_fmt
at src/libstd/sys_common/backtrace.rs:77
3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
at src/libstd/sys_common/backtrace.rs:61
4: core::fmt::write
at src/libcore/fmt/mod.rs:1028
5: std::io::Write::write_fmt
at src/libstd/io/mod.rs:1412
6: std::sys_common::backtrace::_print
at src/libstd/sys_common/backtrace.rs:65
7: std::sys_common::backtrace::print
at src/libstd/sys_common/backtrace.rs:50
8: std::panicking::default_hook::{{closure}}
at src/libstd/panicking.rs:188
9: std::panicking::default_hook
at src/libstd/panicking.rs:205
10: std::panicking::rust_panic_with_hook
at src/libstd/panicking.rs:464
11: std::panicking::begin_panic
at /rustc/50f8aadd746ebc929a752e5ffb133936ee75c52f/src/libstd/panicking.rs:400
12: twitch::twitch_db::TwitchDb::load_products
at src/twitch_db.rs:72
13: twitch::main
at src/bin/twitch.rs:53
14: std::rt::lang_start::{{closure}}
at /rustc/50f8aadd746ebc929a752e5ffb133936ee75c52f/src/libstd/rt.rs:61
15: std::rt::lang_start_internal::{{closure}}
at src/libstd/rt.rs:48
16: std::panicking::try::do_call
at src/libstd/panicking.rs:287
17: __rust_maybe_catch_panic
at src/libpanic_unwind/lib.rs:79
18: std::panicking::try
at src/libstd/panicking.rs:265
19: std::panic::catch_unwind
at src/libstd/panic.rs:396
20: std::rt::lang_start_internal
at src/libstd/rt.rs:47
21: std::rt::lang_start
at /rustc/50f8aadd746ebc929a752e5ffb133936ee75c52f/src/libstd/rt.rs:61
22: main
23: __libc_start_main
24: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

```
RUST_BACKTRACE=full cargo run
warning: unused import: `Read`
--> src/twitch_db.rs:5:15
|
5 | use std::io::{Read, Write};
|               ^^^^
|
= note: `#[warn(unused_imports)]` on by default

warning: unused import: `Product`
--> src/twitch_game.rs:1:33
|
1 | use crate::twitch_db::{Install, Product, TwitchDb};
|                                 ^^^^^^^

warning: field is never used: `auth_scopes`
--> src/twitch_game.rs:30:5
|
30 |     auth_scopes: Option<Vec<String>>,
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default

warning: field is never used: `schema_version`
--> src/twitch_game.rs:37:5
|
37 |     schema_version: String,
|     ^^^^^^^^^^^^^^^^^^^^^^

warning: field is never used: `post_install`
--> src/twitch_game.rs:38:5
|
38 |     post_install: Option<Vec<FuelCommand>>,
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: method is never used: `load`
--> src/twitch_game.rs:110:5
|
110 |     fn load(cache_dir: PathBuf) -> Result<Vec<TwitchGame>, Error> {
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: method is never used: `save`
--> src/twitch_game.rs:117:5
|
117 |     fn save(cache_dir: &PathBuf, games: &Vec<TwitchGame>) -> Result<(), Error> {
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Finished dev [unoptimized + debuginfo] target(s) in 0.17s
Running `target/debug/twitch`
Refreshing Twitch game cache...
thread 'main' panicked at 'assertion failed: product_info_db.exists()', src/twitch_db.rs:72:9
stack backtrace:
0:     0x55c0e112d514 - backtrace::backtrace::libunwind::trace::ha8eb2e16530d8647
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
1:     0x55c0e112d514 - backtrace::backtrace::trace_unsynchronized::h3c03f64808163b85
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
2:     0x55c0e112d514 - std::sys_common::backtrace::_print_fmt::hc8d7c3ead3ca91e9
at src/libstd/sys_common/backtrace.rs:77
3:     0x55c0e112d514 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hfdc0da47c8abfab0
at src/libstd/sys_common/backtrace.rs:61
4:     0x55c0e115148c - core::fmt::write::h9110bebf7c21d6da
at src/libcore/fmt/mod.rs:1028
5:     0x55c0e112b017 - std::io::Write::write_fmt::h54b78469bd8df554
at src/libstd/io/mod.rs:1412
6:     0x55c0e112f94e - std::sys_common::backtrace::_print::h715003a5d83c7a43
at src/libstd/sys_common/backtrace.rs:65
7:     0x55c0e112f94e - std::sys_common::backtrace::print::h68165c007ee97a10
at src/libstd/sys_common/backtrace.rs:50
8:     0x55c0e112f94e - std::panicking::default_hook::{{closure}}::h206e182fa5864b8f
at src/libstd/panicking.rs:188
9:     0x55c0e112f641 - std::panicking::default_hook::he6a9791ad5fe3690
at src/libstd/panicking.rs:205
10:     0x55c0e112ffeb - std::panicking::rust_panic_with_hook::h1d0a65a0a4262a67
at src/libstd/panicking.rs:464
11:     0x55c0e10f6a03 - std::panicking::begin_panic::hd16e09d121ad30f9
at /rustc/50f8aadd746ebc929a752e5ffb133936ee75c52f/src/libstd/panicking.rs:400
12:     0x55c0e0f46669 - twitch::twitch_db::TwitchDb::load_products::hbb02724ea1df7d5a
at src/twitch_db.rs:72
13:     0x55c0e0b41f37 - twitch::main::hb1a652cb020160f4
at src/bin/twitch.rs:53
14:     0x55c0e0b45ad0 - std::rt::lang_start::{{closure}}::h67213c67d2a6a069
at /rustc/50f8aadd746ebc929a752e5ffb133936ee75c52f/src/libstd/rt.rs:61
15:     0x55c0e112fa13 - std::rt::lang_start_internal::{{closure}}::h9ce951d96e69f307
at src/libstd/rt.rs:48
16:     0x55c0e112fa13 - std::panicking::try::do_call::hc878b27ccee62948
at src/libstd/panicking.rs:287
17:     0x55c0e113656a - __rust_maybe_catch_panic
at src/libpanic_unwind/lib.rs:79
18:     0x55c0e11304cd - std::panicking::try::h103b04fd5aa1cf3b
at src/libstd/panicking.rs:265
19:     0x55c0e11304cd - std::panic::catch_unwind::h1e56bee74dbb6b1a
at src/libstd/panic.rs:396
20:     0x55c0e11304cd - std::rt::lang_start_internal::h222d1f0e7218c0c4
at src/libstd/rt.rs:47
21:     0x55c0e0b45aa9 - std::rt::lang_start::hddc743b18ef46a99
at /rustc/50f8aadd746ebc929a752e5ffb133936ee75c52f/src/libstd/rt.rs:61
22:     0x55c0e0b43aaa - main
23:     0x7f424dce1153 - __libc_start_main
24:     0x55c0e0b3d31e - _start
25:                0x0 - <unknown>
```

**Comment by joshuabenuck** [comment]
That is puzzling. The assertion failing is the one looking for a file at `C:\Users\<user>\AppData\Roaming\Twitch\Games\Sql\GameProductInfo.sqlite`. It is one of the two key files holding information about Twitch Prime games.

Does that file exist?
If not, does the `C:\Users\<user>\AppData\Roaming\Twitch\` directory structure exist?
Is Twitch installed in the default location?
Does `C:\ProgramData\Twitch\Games\Sql\GameInstallInfo.sqlite` exist?
Are there any other files in `C:\ProgramData\Twitch\Games\Sql`?

**Comment by joshuabenuck** [comment]
Commit https://github.com/joshuabenuck/twitch/commit/f99beb02502f07223c1884438b6f61549e949c1b changes the error handling for the two sqlite files so they print a more user friendly message about which file cannot be found.

**Comment by D1mon** [comment]
```
Refreshing Twitch game cache...
Product info missing: /home/dimon/.config/Twitch\Games\Sql\GameProductInfo.sqlite
```
there are no folders + files. Probably because the slashes are wrong

**Comment by D1mon** [comment]
fixed slashes. but files are not created. manually created folders and file. Now this error:
```
Refreshing Twitch game cache...
no such table: DbSet
```

now you need to describe the structure of the table

**Comment by joshuabenuck** [comment]
This utility doesn't create those files, it merely reads the files created by the Windows Twitch Desktop client. The path in your comment looks like it is from a Linux or macOS system. This utility will not work there and cannot be made to work there until Twitch adds support for Twitch Prime games on non-Windows platforms.

Commit https://github.com/joshuabenuck/twitch/commit/cce47d1cddddf31cc40eca5f1da66eb7471c72fb adds an error message on non-Windows platforms to avoid any confusion.
